version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-updates:
        update-types:
          - "minor"
          - "patch"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
